### ISSUE TITLE
Nadpisywanie przez pobrane dane

### ISSUE THREAD

**Issue by Draako** [kontentika/kontentika#14]
Po wklepaniu linka do pola adresu, pole tytułu i opisu jest nadpisywane przez pobrane dane.

**Comment by mahho** [comment]
Jest na 0.5 sekundy (o ile mnie pamięc nie myli) timeout ustawiony który pobiera dane. Nie ma (jeszcze) sprawdzania czy już ktoś coś wpisał.

**Comment by Draako** [comment]
O to właśnie mi chodziło - że nadpisuje już wprowadzone dane.

**Comment by kontentika** [comment]
Zmienione, teraz dużo szybciej się ładuje (praktycznie po wklejeniu linka)
Z czasem się pojawi opcja w ustawieniach konta czy ma autouzupełniać pola.
