### ISSUE TITLE
Hasła trzymane sa plaintextem

### ISSUE THREAD

**Issue by agilob** [kontentika/kontentika#18]
Swoje hasło można odczytać w "Zmień hasło"
1. Edytuj element obecnego hasła
2. Zmień `type="password"` na `type="text"` żeby odczytać swoje hasło

Nieładnie :>

**Comment by mahho** [comment]
Możesz mi to "zreprodukować"? Bo nie rozumiem o co chodzi :P
Nie masz gdzieś zapamiętanego hasła w przeglądarce?

**Comment by agilob** [comment]
A dobra, chyba nie mogę :D To było moje hasło zapisane w przeglądarce, samo się wpisało do "obecne hasło".
