### ISSUE TITLE
Treść nie może mieć użytego takiego samego tytułu

### ISSUE THREAD

**Issue by mahho** [kontentika/kontentika#6]
Do poprawy

**Comment by agilob** [comment]
Ciekawy problem, czemu nie? Mogę dodać treść o tym samym tytule do dwóch różnych grup języków programowania "Good testing practices" i obie treści tam pasują. Do ciekawostek może trafić ta sama treść, o tym samym tytule i URI, ale 3lata później, w obu przypadkach powinno być to dozwolone.

**Comment by mahho** [comment]
w obu przypadkach powinno być to dozwolone.
Oczywiście, zdjąłem już wymuszenie unique, ale po dodaniu takiego samego tytułu dopisuje się inkrementacja takiego samego URI

**Comment by kontentika** [comment]
Poprawione
